export enum Colors {
	RED = 'RED',
	BLUE = 'BLUE',
	GREEN = 'GREEN',
	ORANGE = 'ORANGE',
	PURPLE = 'PURPLE',
	YELLOW = 'YELLOW',
	WHITE = 'WHITE',
	BLACK = 'BLACK',
	BROWN = 'BROWN',
	MAGENTA = 'MAGENTA',
}
